### ISSUE TITLE
Error with Capybara 3.37.1

### ISSUE THREAD

**Issue by tonydewan** [yuki24/capybara-shadowdom#1]
We have a couple of Rails system tests that rely on capybara-shadowdom. In an attempt to fix an unrelated issue, we upgraded from capybara 3.36.0 to 3.37.1. Doing so caused the shadowdom tests to fail.

An example of the usage:

```ruby
within(page.find("foo").shadow_root) do
  expect(page).to have_selector(".bar")
end
```

This works with 3.36.0. On 3.37.1, the following error results:

```
Capybara::NotSupportedByDriverError: Capybara::Driver::Node#shadow_root
```

We are using cuprite 0.13 with chromium.

**Comment by tonydewan** [comment]
According to the [Capybara changelog](https://github.com/teamcapybara/capybara/blob/master/History.md#version-3370), 3.37.0 saw the addition of a beta `shadow_root` method. It says:

> [Beta] Element#shadow_root support. Requires selenium-webdriver 4.1+. Only currently supported with Chrome when using the selenium driver. 

My guess is that the on in Capybara is taking precedence over the one from capybara-shadowdom, and the error I see is actually from my driver/browser combo not working with the new on. I'd love for the opposite to be the case, since the one from capybara-shadowdom actually works for me :)

**Comment by tonydewan** [comment]
I now see https://github.com/yuki24/capybara-shadowdom/commit/23c05974674970dd83ed36b48c1bcf2bb93f83d4. Sorry for not digging more before submitting an issue!

Any way to get a new release with that commit?

**Comment by yuki24** [comment]
@tonydewan My apologies for such a long absence! I will cut a new release tomorrow and will let you know once it is done.

**Comment by tonydewan** [comment]
Great, thanks!

**Comment by yuki24** [comment]
[`v0.3.0`](https://github.com/yuki24/capybara-shadowdom/releases/tag/v0.3.0) is out now. Thank you for your patience!
